#!/bin/sh

tree="$1"
if [ "$#" -ne "1" -o -z "$tree" -o ! -e "$tree/configure" ]
then
	cat <<-tac
		USAGE: `basename "$0"` <path to binutils source tree>

		Note that source tarballs to not include the simulator (run command);
		for that, you must clone the full binutils-gdb repository.
	tac
	exit 1
fi

exec "$tree/configure" --prefix=/usr/local --target=riscv32 --disable-gdb --disable-gold --disable-gprof --disable-gprofng
