#!/bin/sh

dir="`dirname "$0"`"
clang="`printf "%s\n" "$dir/clang+llvm-"*"/bin/clang" | sort | tail -n1`"
zstd="`printf "%s\n" "$dir/zstd-"*"/lib/libzstd.1.dylib" | sort | tail -n1`"
DYLD_LIBRARY_PATH="`dirname $zstd`:$DYLD_LIBRARY_PATH" exec "$clang" -target riscv32 -march=rv32i "$@"
